ISO_IN := CentOS-6.5-x86_64-minimal.iso
ISO_OUT := centos-6.5-custom.iso
# CentOS 6 doesn't actually care about the disk label, but CentOS 7 does, so we
# include the option here as well:
ISO_LABEL := 'CentOS 6 x86_64'
MIRROR := http://mirror.us.leaseweb.net/centos/6.5/isos/x86_64

include ../Makefile.common
