ISO_IN := CentOS-7.0-1406-x86_64-Minimal.iso
ISO_OUT := centos-7.0-1406-custom.iso
ISO_LABEL := 'CentOS 7 x86_64'
MIRROR := http://mirror.us.leaseweb.net/centos/7.0.1406/isos/x86_64

include ../Makefile.common
